"""Original transfer questions. Keys correspond to the published course IDs."""
RAW = r'''
4e-sciences-physiques|Deux expériences donnent des résultats différents. Faut-il immédiatement rejeter l’hypothèse ?|Il faut d’abord comparer les conditions, les instruments et la répétabilité. Une différence peut venir d’un facteur non contrôlé ou d’une erreur de mesure. On répète dans des conditions comparables avant de conclure ; l’hypothèse doit rester confrontée aux observations.
4e-grandeurs-mesures|Une salle mesure 4 m sur 3 m. Donner sa surface en m² puis en cm².|La surface vaut 4 × 3 = 12 m². Comme 1 m = 100 cm, 1 m² = 10 000 cm² ; donc 12 m² = 120 000 cm². Il faut mettre le facteur de conversion au carré pour une surface.
4e-masse-volumique|Deux objets ont la même masse mais des volumes différents. Lequel a la plus grande masse volumique ?|La masse volumique vaut ρ = m/V. À masse égale, le plus petit volume donne la plus grande masse volumique. Cela ne signifie pas que cet objet est plus lourd : les masses sont égales. On compare le quotient, en conservant des unités compatibles.
4e-poids-masse|Un objet de 2 kg est transporté dans un lieu où g = 4 N/kg. Que deviennent sa masse et son poids ?|La masse reste 2 kg : elle caractérise la quantité de matière de l’objet. Le poids vaut P = mg = 2 × 4 = 8 N dans ce lieu. Une balance et un dynamomètre ne mesurent donc pas la même grandeur.
4e-melanges-corps-purs|Comment séparer un mélange d’eau, de sable et de sel dissous ?|Filtrer d’abord pour retenir le sable. Le sel dissous traverse le filtre avec l’eau. Pour récupérer le sel, on peut ensuite évaporer l’eau ; pour récupérer aussi de l’eau, on réalise une distillation avec un dispositif adapté. Une filtration seule ne sépare pas le sel dissous.
4e-mole|Une quantité de 0,50 mol contient-elle moins d’entités qu’une mole ? Justifier.|Oui : N = nN_A. Avec N_A ≈ 6,02 × 10²³ mol⁻¹, on obtient N ≈ 3,01 × 10²³ entités. C’est la moitié des entités d’une mole. Il faut préciser si les entités considérées sont des atomes, des molécules ou des ions.
4e-reaction-chimique|Dans un système fermé, 4 g de réactif A réagissent avec 7 g de réactif B sans excès. Quelle masse totale de produits obtient-on ?|La masse totale est conservée : 4 + 7 = 11 g. Les atomes se réorganisent sans disparaître. La conclusion suppose un système fermé et que les masses indiquées correspondent aux seuls réactifs consommés ; un gaz qui s’échappe fausserait une pesée ouverte.
4e-structure-matiere|Pourquoi un atome neutre n’est-il pas un objet dépourvu de charges ?|Il contient des protons positifs et des électrons négatifs en nombres égaux. Leurs charges se compensent à l’échelle de l’atome. Neutre signifie une charge totale nulle, et non une absence de particules chargées. Les neutrons ne portent pas de charge électrique.
4e-circuit-electrique|Pourquoi un interrupteur dans le conducteur commun n’a-t-il pas le même effet qu’un interrupteur dans une seule branche d’un circuit en dérivation ?|L’interrupteur commun peut interrompre le chemin nécessaire à toutes les branches. Dans une seule branche, il interrompt uniquement cette branche si les autres boucles restent fermées. Il faut suivre chaque trajet complet du courant sur le schéma plutôt que se fier à la proximité des éléments.
4e-sources-lumiere|La Lune est-elle une source primaire de lumière visible ?|Non. La lumière visible reçue de la Lune est principalement celle du Soleil qu’elle diffuse. Le Soleil est une source primaire ; la Lune est un objet diffusant. Un objet peut être visible sans produire lui-même la lumière qui parvient à l’œil.
4e-propagation-lumiere|Pourquoi une ombre permet-elle d’illustrer la propagation rectiligne de la lumière ?|Dans un milieu homogène et transparent, les rayons suivent des lignes droites. Un objet opaque empêche certains rayons d’atteindre l’écran et crée une région moins éclairée. La forme de l’ombre dépend aussi de la taille et de la position de la source.
4e-reflexion-refraction|Un rayon arrive avec un angle de 35° par rapport à la normale sur un miroir. Quel angle fait le rayon réfléchi avec le miroir ?|L’angle de réflexion par rapport à la normale vaut 35°. La normale étant perpendiculaire au miroir, le rayon réfléchi fait 90° − 35° = 55° avec la surface. Les angles de la loi de réflexion se mesurent depuis la normale.
4e-fractions|Calculer 3/4 − 1/6, puis vérifier le signe du résultat.|Au dénominateur commun 12 : 3/4 = 9/12 et 1/6 = 2/12. La différence vaut 7/12. Elle est positive, ce qui est cohérent puisque 3/4 est supérieur à 1/6. On ne soustrait pas les dénominateurs.
4e-puissances|Simplifier (2³ × 2⁴)/2².|Pour une même base non nulle, on additionne les exposants à la multiplication et on les soustrait à la division : 2^(3+4−2) = 2⁵ = 32. Ces règles ne permettent pas d’additionner les exposants dans une somme.
4e-calcul-litteral|Développer puis réduire 3(2x−1)−2(x+4).|La distributivité donne 6x−3−2x−8, puis 4x−11. Le signe moins devant 2(x+4) affecte les deux termes. On peut vérifier avec x = 1 : l’expression initiale et la forme réduite valent toutes deux −7.
4e-proportionnalite|Quatre cahiers coûtent 1 200 FCFA. Combien coûtent sept cahiers identiques sans remise ?|Le prix unitaire vaut 1 200/4 = 300 FCFA. Sept cahiers coûtent 7 × 300 = 2 100 FCFA. La proportionnalité suppose ici un même prix unitaire et aucune remise ni frais fixe.
4e-triangle-rectangle|Un triangle rectangle a pour côtés de l’angle droit 5 cm et 12 cm. Calculer l’hypoténuse.|Le théorème de Pythagore donne c² = 5² + 12² = 169, donc c = 13 cm. L’hypoténuse est opposée à l’angle droit et doit être le côté le plus long. On applique ce théorème après avoir identifié le triangle rectangle.
3e-courant-electrisation|Un objet gagne des électrons. Quel signe prend sa charge nette ?|Sa charge nette devient négative, car l’électron porte une charge négative. Dans un transfert ordinaire, les protons restent dans les noyaux. La conservation de la charge impose de tenir compte de l’objet qui a cédé ces électrons.
3e-dispersion|Pourquoi une lumière monochromatique n’est-elle pas décomposée en plusieurs couleurs par un prisme idéal ?|Elle comporte une seule fréquence. Le prisme peut dévier le rayon, mais il ne crée pas les différentes fréquences d’une lumière blanche. La dispersion sépare des composantes déjà présentes parce que la réfraction dépend de la longueur d’onde.
3e-energie-rendement|Une machine reçoit 2 000 J avec un rendement de 75 %. Quelle énergie utile fournit-elle ?|η = E_u/E_r, donc E_u = 0,75 × 2 000 = 1 500 J. Les 500 J restants sont transférés ou convertis sous des formes moins utiles au but recherché. Utiliser 75 au lieu de 0,75 donnerait un résultat impossible pour ce bilan.
3e-forces|Un livre immobile est posé sur une table horizontale. Quelles forces principales agissent sur lui ?|Le poids, dirigé vers le bas, et la réaction normale de la table, dirigée vers le haut. Dans ce modèle simple, leurs résultantes se compensent. L’immobilité ne signifie pas absence de forces ; elle impose ici une résultante nulle.
3e-hydrocarbures|Pourquoi faut-il une ventilation suffisante lors d’une combustion d’hydrocarbure ?|Une combustion incomplète peut produire du monoxyde de carbone, un gaz toxique. La disponibilité en dioxygène et l’évacuation des produits sont essentielles. Une activité scolaire ne doit jamais consister à brûler un combustible dans un espace fermé ou sans encadrement.
3e-metaux|Pourquoi ne peut-on pas reconnaître sûrement un métal seulement à sa couleur ?|Des métaux et des alliages peuvent avoir des aspects proches, et une couche d’oxyde peut modifier leur surface. On croise plusieurs propriétés : conductivité, masse volumique, comportement magnétique selon le matériau et contexte. Une seule observation ne suffit pas à une identification certaine.
3e-resistances|Deux résistances de 10 Ω et 20 Ω sont en série sous 6 V. Calculer l’intensité.|La résistance équivalente vaut 10 + 20 = 30 Ω. L’intensité vaut I = U/R = 6/30 = 0,20 A. Ce courant traverse les deux résistances. Leurs tensions diffèrent : 2 V et 4 V, dont la somme est 6 V.
3e-travail-puissance|Une machine fournit 600 J en 20 s. Une autre fournit le même travail en 10 s. Comparer les puissances.|P₁ = 600/20 = 30 W et P₂ = 600/10 = 60 W. Le travail est identique, mais la deuxième machine le fournit deux fois plus vite. La puissance est un débit d’énergie ; ce n’est pas une énergie totale.
3e-acides-bases|Une solution a un pH de 3 à température usuelle. Que peut-on dire, et que ne peut-on pas conclure ?|Elle est acide dans les conditions usuelles de ce chapitre. Le pH seul ne donne pas l’identité du soluté ni sa concentration analytique sans modèle supplémentaire. Ne jamais goûter une solution pour l’identifier ; utiliser un indicateur ou un pH-mètre adapté.
3e-racines|Simplifier √98 et vérifier par élévation au carré.|98 = 49 × 2, donc √98 = 7√2. Son carré vaut 49 × 2 = 98, et 7√2 est positif. La racine carrée principale est positive ; elle ne représente pas les deux solutions de x² = 98.
3e-thales|Dans un triangle ABC, M est sur AB, N sur AC et MN est parallèle à BC. Si AM/AB = 2/3 et BC = 9 cm, calculer MN.|La configuration de Thalès donne MN/BC = AM/AB = 2/3. Donc MN = 9 × 2/3 = 6 cm. Le rapport correspond aux mêmes positions sur les côtés ; il faut préciser le parallélisme avant d’appliquer le théorème.
3e-trigonometrie|Dans un triangle rectangle, un angle aigu a pour côté adjacent 4 cm et pour hypoténuse 5 cm. Donner son cosinus.|Le cosinus vaut adjacent/hypoténuse = 4/5 = 0,8. Les mots opposé et adjacent dépendent de l’angle choisi. Le résultat est compris entre 0 et 1, ce qui constitue un contrôle cohérent pour un angle aigu.
3e-systemes|Résoudre x+y = 11 et x−y = 3.|En additionnant les équations, 2x = 14, donc x = 7. Dans x+y = 11, y = 4. Vérification : 7+4 = 11 et 7−4 = 3. Une solution doit satisfaire les deux équations simultanément.
3e-fonctions-affines|Pour f(x)=−2x+5, déterminer f(3), puis l’antécédent de 1.|f(3)=−6+5=−1. Pour l’antécédent de 1, on résout −2x+5=1, soit x=2. Image et antécédent répondent à deux questions différentes : calculer une valeur ou résoudre une équation.
3e-statistiques|Dans une série de valeurs 2, 3, 3, 8, calculer la moyenne et la médiane.|La moyenne vaut (2+3+3+8)/4 = 4. La médiane est la moyenne des deux valeurs centrales ordonnées : (3+3)/2 = 3. La valeur 8 tire la moyenne vers le haut ; moyenne et médiane ne décrivent pas exactement le même aspect.
3e-equations-problemes|Résoudre 5x−6 = 2x+9 et vérifier la réponse.|On soustrait 2x puis on ajoute 6 aux deux membres : 3x = 15, donc x = 5. Vérification : 5×5−6 = 19 et 2×5+9 = 19. Les transformations doivent préserver l’égalité à chaque étape.
3e-solutions-aqueuses|On dissout 3 g de soluté pour obtenir 150 mL de solution. Calculer la concentration massique.|Le volume final vaut 0,150 L. C_m = m/V = 3/0,150 = 20 g/L. Le dénominateur correspond au volume de la solution finale. Écrire 150 sans convertir donnerait une valeur en g/mL et non en g/L.
seconde-ensembles|Si A={1,2,3} et B={3,4}, déterminer A∩B et A∪B.|L’intersection contient les éléments communs : A∩B={3}. L’union contient les éléments appartenant à au moins un des ensembles : A∪B={1,2,3,4}. On ne répète pas un élément dans l’écriture d’un ensemble.
seconde-fonctions|Pour f(x)=1/(x+3), donner le domaine et l’image de 1.|Le dénominateur doit être non nul : x≠−3. Le domaine est ℝ privé de −3 et f(1)=1/4. Une valeur exclue ne peut pas être utilisée comme entrée. On doit distinguer cette restriction du calcul d’une image dans le domaine.
seconde-polynomes|Simplifier (x²−4)/(x−2), en conservant le domaine.|x²−4=(x−2)(x+2). Pour x≠2, le quotient vaut x+2. L’expression initiale reste indéfinie en 2 : la simplification ne supprime pas cette restriction. Le polynôme x+2 défini partout est une autre fonction si l’on élargit son domaine.
seconde-vecteurs|A(−2,1) et B(2,4). Donner les coordonnées et la norme du vecteur AB.|AB=(2−(−2),4−1)=(4,3). Dans un repère orthonormé, sa norme vaut √(4²+3²)=5. BA=(−4,−3) a la même norme et le sens opposé. Attention à la soustraction d’une coordonnée négative.
premiere-denombrement|Combien de codes de trois chiffres peut-on former avec 0 à 9 sans aucune répétition, zéro initial autorisé ?|Il y a 10 choix pour la première position, puis 9 et enfin 8 puisque chaque chiffre utilisé est retiré. Le nombre de codes vaut 10×9×8 = 720. L’ordre compte : 012 et 021 sont deux codes différents. Ce calcul diffère du cas où les répétitions sont autorisées.
premiere-produit-scalaire|Dans un repère orthonormé, u=(2,−1) et v=(1,2). Sont-ils orthogonaux ?|Le produit scalaire vaut 2×1+(−1)×2 = 0. Les deux vecteurs sont donc orthogonaux. Cette formule par coordonnées suppose un repère orthonormé ; elle ne se transfère pas sans adaptation à une base quelconque.
premiere-second-degre|Résoudre x²−7x+10=0.|On factorise en (x−2)(x−5)=0. Un produit est nul si au moins un facteur est nul : les solutions sont 2 et 5. Le discriminant vaut aussi 49−40=9, ce qui confirme deux racines réelles distinctes.
premiere-suites|Une suite arithmétique vérifie u₀=5 et a pour raison 3. Calculer u₄.|u_n=u₀+nr, donc u₄=5+4×3=17. Il y a quatre passages de u₀ à u₄. Si le premier terme avait été indexé u₁, la formule avec cet indice aurait été différente.
'''
EXTRAS = {line.split('|',2)[0]: tuple(line.split('|',2)[1:]) for line in RAW.strip().splitlines()}
RAW_LYCEE = r'''
seconde-s-electrisation|Deux sphères conductrices identiques portent +8 nC et −2 nC. Après contact puis séparation, quelle charge porte chacune ?|La charge totale conservée vaut +6 nC. Pour deux sphères identiques, isolées des influences extérieures, le partage à l’équilibre est égal : chacune porte +3 nC. Le résultat dépend de l’identité des sphères ; on ne partage pas toujours une charge également entre conducteurs différents.
seconde-s-courant|Pourquoi le sens conventionnel du courant diffère-t-il du déplacement des électrons dans un fil métallique ?|Le sens conventionnel est celui d’un déplacement de charges positives. Les électrons sont négatifs : leur déplacement produit un courant conventionnel de sens opposé. Dans un électrolyte, les ions positifs et négatifs peuvent tous deux transporter la charge.
seconde-s-intensite|Dans un nœud, 0,8 A entrent ; 0,3 A sortent par une branche. Quelle intensité sort par la seconde branche ?|La conservation de la charge donne la somme des intensités entrantes égale à celle des sortantes. Donc 0,8=0,3+I et I=0,5 A. On doit vérifier le sens choisi pour chaque branche avant d’écrire l’équation.
seconde-s-tension|Si U_AB=−4 V et U_BC=9 V, calculer U_AC puis U_CA.|U_AC=U_AB+U_BC=−4+9=5 V. Inverser les points donne U_CA=−5 V. Les tensions sont algébriques : leur signe fait partie de l’information, et une addition de valeurs absolues serait incorrecte.
seconde-s-dipoles-passifs|Une résistance de 150 Ω est traversée par 20 mA. Calculer sa tension.|20 mA=0,020 A. U=RI=150×0,020=3,0 V. La loi d’Ohm décrit le conducteur ohmique dans ses conditions d’utilisation ; tous les dipôles passifs n’ont pas une caractéristique linéaire.
seconde-s-dipoles-actifs|Un générateur a E=12 V et r=2 Ω. Quelle tension délivre-t-il quand I=1,5 A ?|En convention générateur, U=E−rI=12−2×1,5=9 V. À vide, I=0 et U=E. La résistance interne explique la baisse de tension sous charge dans ce modèle linéaire.
seconde-s-amplification|Un amplificateur idéal fonctionne avec un gain en tension de 5. Pour une entrée de 0,2 V, quelle sortie prévoit le modèle ?|U_s=G U_e=5×0,2=1,0 V. Cette prédiction est valable dans le domaine linéaire du montage. La sortie ne peut pas dépasser les limites imposées par l’alimentation ; une amplification ne crée pas de l’énergie sans source.
seconde-s-mouvement|Une voiture parcourt 150 m en 10 s. Peut-on affirmer qu’elle roule à 15 m/s à chaque instant ?|La vitesse moyenne vaut 150/10=15 m/s. Cela ne garantit pas une vitesse instantanée constante : la voiture peut accélérer puis ralentir. Pour conclure à un mouvement uniforme, il faut des informations supplémentaires sur l’évolution de sa position.
seconde-s-forces|Deux forces colinéaires de 8 N et 3 N agissent en sens opposés. Donner leur résultante.|La résultante a une norme de 8−3=5 N et le sens de la force de 8 N. Les forces s’additionnent comme des vecteurs. Une addition de normes 8+3 conviendrait à des forces colinéaires de même sens.
seconde-s-poids-masse|Un objet a une masse de 500 g dans un lieu où g=9,8 N/kg. Calculer son poids.|500 g=0,500 kg. P=mg=0,500×9,8=4,9 N. La masse se mesure en kilogrammes, le poids en newtons. Préciser la valeur locale de g permet de distinguer propriété de l’objet et interaction gravitationnelle.
seconde-s-equilibre-forces|Un objet subit seulement deux forces et reste en équilibre. Quelles conditions ces forces doivent-elles remplir ?|Pour un solide en équilibre sous deux forces, elles ont la même droite d’action, la même intensité et des sens opposés. La résultante est nulle et aucun couple ne subsiste. Deux forces opposées sur des droites parallèles distinctes peuvent créer un moment.
seconde-s-moments|Une force perpendiculaire produit un moment de norme 12 N·m à 0,40 m d’un axe. Calculer sa norme.|M=Fd, donc F=M/d=12/0,40=30 N. d est la distance perpendiculaire à la droite d’action. Le signe du moment dépend du sens de rotation choisi ; les données fournissent ici sa norme.
seconde-s-propagation|Un rayon lumineux traverse de l’air homogène. Que faut-il changer dans le milieu pour qu’une direction différente devienne possible ?|Dans l’approximation de l’optique géométrique, le trajet est rectiligne dans un milieu homogène. Une interface avec un autre milieu peut provoquer une réfraction ; un gradient d’indice peut aussi courber le trajet. L’affirmation rectiligne dépend donc de l’homogénéité.
seconde-s-reflexion|L’angle entre un rayon incident et la surface d’un miroir est 20°. Donner l’angle de réflexion par rapport à la normale.|L’incidence par rapport à la normale vaut 90°−20°=70°. L’angle de réflexion vaut alors 70°. Les rayons incident et réfléchi restent dans le plan d’incidence ; la normale doit être tracée au point d’arrivée.
seconde-s-refraction-dispersion|La lumière passe de l’air dans un verre d’indice 1,5 avec i=30°. Calculer sin r.|La loi de Snell-Descartes donne n₁ sin i=n₂ sin r. Avec n₁≈1 : sin r=sin30°/1,5=1/3. Le rayon se rapproche de la normale, puisque l’indice augmente. r≈19,5° si l’on utilise la fonction arcsinus.
seconde-s-melanges|Pourquoi de l’eau salée limpide n’est-elle pas nécessairement un corps pur ?|Elle peut contenir du sel dissous tout en formant une seule phase visible. Un mélange homogène paraît uniforme, mais contient plusieurs espèces. L’aspect seul ne prouve pas la pureté ; on peut notamment analyser ses propriétés ou séparer les constituants.
seconde-s-atomes|Un atome neutre a Z=13 et A=27. Combien possède-t-il de protons, neutrons et électrons ?|Il possède 13 protons, A−Z=14 neutrons et 13 électrons puisqu’il est neutre. Z identifie l’élément ; A compte les nucléons. Une ionisation modifie le nombre d’électrons sans modifier le noyau dans le cadre chimique.
seconde-s-ions|Un atome neutre perd deux électrons. Quelle est la charge de l’ion obtenu ?|Il devient un cation de charge +2e, soit environ +3,20×10⁻¹⁹ C. Perdre des charges négatives rend la charge nette positive. Les protons du noyau ne se déplacent pas lors de cette ionisation chimique.
seconde-s-liaisons|Dans une molécule H₂, que représente la liaison covalente entre les deux atomes ?|Les deux atomes partagent une paire d’électrons. Chaque atome d’hydrogène peut ainsi atteindre un duet dans ce modèle. Une liaison covalente n’est pas un transfert complet d’électron donnant deux ions ; cette distinction aide à interpréter les représentations de Lewis.
seconde-s-mole|Calculer la masse de 0,25 mol d’eau si M(H₂O)=18 g/mol.|m=nM=0,25×18=4,5 g. La quantité de matière est exprimée en moles et la masse molaire en grammes par mole ; leur produit donne des grammes. Il faut identifier l’espèce avant d’utiliser sa masse molaire.
seconde-s-equation-bilan|Équilibrer la combustion du méthane : CH₄ + O₂ → CO₂ + H₂O.|CH₄+2O₂→CO₂+2H₂O. On compte un atome de carbone, quatre d’hydrogène et quatre d’oxygène de chaque côté. Les coefficients peuvent être modifiés, mais les indices des formules des espèces ne doivent pas être changés.
seconde-s-solutions|Préparer 250 mL d’une solution contenant 0,05 mol de soluté. Calculer sa concentration molaire.|V=0,250 L. C=n/V=0,05/0,250=0,20 mol/L. Le volume est celui de la solution finale. Pour une préparation réelle, on dissout puis complète au trait de jauge avec un dispositif et des consignes adaptés.
seconde-s-solution-acide|Pourquoi une dilution d’acide fort tend-elle à faire augmenter le pH ?|Diluer diminue la concentration des ions oxonium apportés par l’acide. Comme pH=−log[H₃O⁺] dans le modèle usuel dilué, le pH augmente. Près de la neutralité, l’autoprotolyse de l’eau doit être prise en compte ; on ne prolonge pas indéfiniment une formule simplifiée.
seconde-s-solution-basique|À 25 °C, une solution a pH=11. Est-elle basique ? Donner le pOH.|Oui : le pH est supérieur à 7 à 25 °C. Dans le modèle usuel, pH+pOH=14, donc pOH=3. La valeur de neutralité dépend de la température ; le nombre 7 n’est pas une constante universelle à toutes les températures.
seconde-s-ph-indicateurs|Pourquoi un indicateur coloré ne donne-t-il pas toujours une valeur précise du pH ?|Sa couleur dépend d’une zone de virage et renseigne surtout sur un intervalle de pH. Une lecture précise exige un pH-mètre étalonné et un protocole adapté. La couleur doit être interprétée avec la gamme de l’indicateur, pas avec une règle universelle.
premiere-s2-travail-puissance|Une force constante de 10 N agit sur 5 m avec un angle de 60° au déplacement. Calculer son travail.|W=Fd cosθ=10×5×0,5=25 J. Le travail est positif puisque la composante de la force favorise le déplacement. La formule exige une force constante et l’angle entre la force et le déplacement, non avec une direction arbitraire.
premiere-s2-energie-cinetique|Un objet de 2 kg double sa vitesse de 3 m/s à 6 m/s. Comparer ses énergies cinétiques.|E_c=½mv². Initialement E_c=9 J ; finalement E_c=36 J. Doubler la vitesse multiplie donc l’énergie cinétique par quatre à masse constante. Le théorème de l’énergie cinétique relie leur différence aux travaux des forces.
premiere-s2-energie-mecanique|Une balle tombe sans frottements dans un champ uniforme. Comment évoluent ses énergies ?|Son énergie potentielle de pesanteur diminue et son énergie cinétique augmente. Leur somme, l’énergie mécanique, reste constante dans ce modèle. La conservation n’est pas automatique si une force dissipative comme un frottement exerce un travail.
premiere-s2-calorimetrie|Chauffer 0,20 kg d’eau de 20 °C à 30 °C, avec c=4 180 J/(kg·K). Calculer l’énergie reçue.|Q=mcΔT=0,20×4 180×10=8 360 J. Un écart de 10 °C est aussi un écart de 10 K. Cette relation suppose l’absence de changement d’état et une capacité thermique massique traitée comme constante dans cet intervalle.
premiere-s2-champ-electrostatique|Une charge q=+2 µC se trouve dans un champ uniforme de 3 000 N/C. Quelle force subit-elle ?|F=qE=2×10⁻⁶×3 000=0,006 N. Pour une charge positive, la force a le sens du champ. Une charge négative subirait une force de sens opposé ; la relation vectorielle est F=qE.
premiere-s2-potentiel-electrostatique|Une charge positive q=2 µC passe de V_A=10 V à V_B=4 V. Calculer le travail de la force électrique.|W_AB=q(V_A−V_B)=2×10⁻⁶×6=12×10⁻⁶ J. Le travail est positif : la charge positive passe vers un potentiel plus faible. Le potentiel et le champ sont liés, mais ce sont des grandeurs différentes.
premiere-s2-condensateurs|Un condensateur de 10 µF est sous 12 V. Calculer sa charge et son énergie.|Q=CU=10×10⁻⁶×12=120 µC. E=½CU²=0,5×10×10⁻⁶×144=0,00072 J. La charge et l’énergie ne suivent pas la même dépendance à la tension ; l’énergie varie comme U².
premiere-s2-energie-electrique|Une résistance sous 12 V est traversée par 0,5 A pendant 60 s. Calculer l’énergie reçue.|P=UI=12×0,5=6 W. E=PΔt=6×60=360 J. Cette valeur correspond à des grandeurs constantes sur la durée. Dans une résistance, l’énergie électrique reçue est convertie en énergie thermique par effet Joule.
premiere-s2-aop-derivee-integrale|Pour un montage inverseur idéal, R_f=20 kΩ et R_e=10 kΩ. Quel gain et quelle sortie pour U_e=0,5 V ?|En régime linéaire avec rétroaction négative, G=−R_f/R_e=−2. Donc U_s=−1 V. Le signe traduit l’inversion. Cette formule ne convient pas à un montage saturé ; il faut vérifier les limites de l’alimentation.
premiere-s2-ondes|Une onde a une fréquence de 50 Hz et une célérité de 200 m/s. Calculer sa longueur d’onde.|λ=v/f=200/50=4 m. La période vaut T=1/f=0,020 s. La fréquence est imposée par la source ; la célérité dépend du milieu, ce qui peut modifier la longueur d’onde lors d’un changement de milieu.
premiere-s2-lentilles|Une lentille convergente a f′=20 cm. Calculer sa vergence.|f′=0,20 m, donc C=1/f′=+5 dioptries. Le signe positif indique une lentille convergente dans la convention usuelle. Utiliser 20 sans convertir les centimètres en mètres donnerait une valeur cent fois trop petite.
premiere-s2-chimie-organique|Pourquoi une formule brute ne suffit-elle pas toujours à identifier une molécule organique ?|Plusieurs structures peuvent avoir le même nombre d’atomes de chaque élément : ce sont des isomères. La formule semi-développée précise les connexions. Les propriétés dépendent de la structure et des groupes caractéristiques, pas seulement de la formule brute.
premiere-s2-alcanes|Donner la formule brute d’un alcane acyclique à six atomes de carbone.|La formule générale est C_nH_(2n+2). Pour n=6, elle donne C₆H₁₄. Plusieurs isomères peuvent correspondre à cette formule ; elle ne détermine pas la forme de la chaîne. L’expression générale concerne les alcanes acycliques saturés.
premiere-s2-alcenes-alcynes|Comparer les formules d’un alcène acyclique à une double liaison et d’un alcyne acyclique à une triple liaison, pour n=3.|L’alcène a la formule C_nH_(2n), donc C₃H₆ ; l’alcyne C_nH_(2n−2), donc C₃H₄. Les relations supposent une chaîne ouverte et une seule insaturation de la nature indiquée. Elles ne suffisent pas à déterminer toute la structure.
premiere-s2-benzene|Pourquoi représenter le benzène comme un cycle avec trois doubles liaisons fixes est-il une simplification ?|Les électrons π sont délocalisés sur le cycle aromatique. Les écritures de Kekulé sont des représentations limites, pas une alternance de liaisons localisées qui resterait fixe. Cette délocalisation explique notamment la stabilité particulière du benzène.
premiere-s2-composes-oxygenes|Comment distinguer un alcool et un acide carboxylique sur une formule semi-développée ?|Un alcool présente un groupe hydroxyle −OH lié à un carbone saturé dans le cadre usuel. Un acide carboxylique présente −COOH, qui comprend aussi un carbonyle. Il faut examiner l’ensemble du groupe caractéristique, pas seulement repérer les lettres O et H.
premiere-s2-couple-redox|Dans le couple Ag⁺/Ag, écrire la demi-équation de réduction et vérifier la charge.|Ag⁺+e⁻→Ag. L’ion argent capte un électron et devient l’argent métallique. La charge totale à gauche vaut +1−1=0, comme à droite. Le coefficient des électrons vient de la conservation de la charge, pas d’un nombre choisi arbitrairement.
premiere-s2-classement-qualitatif|Si le zinc réduit les ions Cu²⁺ dans les conditions observées, que révèle l’expérience ?|Le zinc cède des électrons et joue le rôle de réducteur ; Cu²⁺ les capte et joue le rôle d’oxydant. La réaction Zn+Cu²⁺→Zn²⁺+Cu permet une comparaison qualitative des couples dans ces conditions. Une observation doit être reliée aux espèces présentes et à leur concentration.
premiere-s2-classement-quantitatif|Une pile a E° cathode=+0,34 V et E° anode=−0,76 V. Calculer sa force électromotrice standard.|E° pile=E° cathode−E° anode=0,34−(−0,76)=1,10 V. Les potentiels sont ceux de réduction. Cette valeur concerne les conditions standard ; les concentrations réelles peuvent modifier la tension de la pile.
premiere-s2-redox-solution|Équilibrer Fe²⁺→Fe³⁺ comme demi-équation d’oxydation.|Fe²⁺→Fe³⁺+e⁻. L’atome de fer est conservé ; à droite, la charge totale vaut +3−1=+2. L’oxydation correspond à une perte d’électrons, donc les électrons apparaissent du côté des produits.
premiere-s2-redox-seche|Dans 2Mg+O₂→2MgO, identifier l’élément oxydé et l’élément réduit.|Le magnésium passe du nombre d’oxydation 0 à +II : il est oxydé. L’oxygène passe de 0 à −II : il est réduit. Ce suivi des nombres d’oxydation permet d’analyser une réaction même sans ions libres en solution.
premiere-s2-electrolyse|Pendant une électrolyse, à quelle électrode a lieu la réduction ?|La réduction a lieu à la cathode. Les électrons y sont fournis par le circuit extérieur pour être captés par une espèce. Oxydation à l’anode et réduction à la cathode restent les définitions ; le signe des électrodes dépend du type de dispositif.
premiere-s2-phosphates-engrais-plastiques|Pourquoi un apport excessif d’engrais phosphatés peut-il poser un problème environnemental ?|Une partie des phosphates peut rejoindre les eaux et favoriser une croissance excessive d’organismes photosynthétiques. Leur décomposition peut réduire le dioxygène disponible : c’est une composante de l’eutrophisation. Le raisonnement doit relier apport, transport et effets plutôt que supposer que tout engrais reste fixé dans le sol.
'''
EXTRAS.update({line.split('|',2)[0]: tuple(line.split('|',2)[1:]) for line in RAW_LYCEE.strip().splitlines()})
RAW_TERMINALE = r'''
terminale-cinematique|Un mouvement rectiligne vérifie x(t)=−t²+6t+2 en unités SI. Calculer v(t), a(t) et l’instant où la vitesse s’annule.|v(t)=dx/dt=−2t+6 m/s et a(t)=dv/dt=−2 m/s². La vitesse s’annule à t=3 s. Une vitesse nulle à cet instant n’implique pas une accélération nulle ; le mobile peut changer de sens.
terminale-dynamique|Un objet de 2 kg a une accélération de 3 m/s² dans un référentiel galiléen. Donner la résultante des forces.|La deuxième loi de Newton donne ΣF=ma. La résultante a donc une norme de 6 N et la direction ainsi que le sens de l’accélération. Ce résultat porte sur la somme vectorielle des forces, pas nécessairement sur chacune d’elles.
terminale-applications-dynamique|Un mobile glisse sur un plan horizontal avec une force motrice de 10 N et un frottement de 4 N. Pour m=2 kg, calculer son accélération horizontale.|Les forces horizontales donnent une résultante de 10−4=6 N vers l’avant. Dans un référentiel galiléen, a=6/2=3 m/s². Le poids et la réaction normale se compensent verticalement dans ce modèle ; ils ne s’ajoutent pas aux normes horizontales.
terminale-gravitation|Si la distance entre deux masses est multipliée par deux, comment varie la force gravitationnelle ?|F=Gm₁m₂/r². À masses constantes, remplacer r par 2r divise la force par quatre. La distance est celle entre les centres pour des corps sphériques dans le modèle utilisé ; ne pas confondre altitude et distance au centre d’un astre.
terminale-particule-champ|Une charge q=−2 µC est dans un champ électrique de 1 000 N/C. Donner la norme et le sens de sa force.|La norme vaut |q|E=2×10⁻⁶×1 000=0,002 N. Comme la charge est négative, la force est opposée au champ. Cette inversion de sens est essentielle avant de déterminer l’accélération ou de tracer une trajectoire.
terminale-oscillations-mecaniques|Un oscillateur idéal a m=0,36 kg et k=100 N/m. Calculer sa pulsation propre.|ω₀=√(k/m)=√(100/0,36)≈16,7 rad/s. La période vaut 2π/ω₀≈0,377 s. Le modèle suppose un ressort linéaire sans amortissement ; l’amplitude n’intervient pas dans la fréquence de ce modèle.
terminale-interferences|Dans l’expérience de Young, λ=500 nm, D=2 m et a=1 mm. Calculer l’interfrange.|i=λD/a=(500×10⁻⁹×2)/(1×10⁻³)=0,001 m=1 mm. Toutes les longueurs doivent être converties dans une même unité. Cette formule utilise les approximations géométriques usuelles et des sources cohérentes.
terminale-champ-magnetique|Une boussole indique-t-elle directement la norme du champ magnétique ?|Une petite boussole indique principalement la direction du champ dans le plan où son aiguille peut pivoter. Elle ne donne pas directement sa norme. Une mesure quantitative nécessite un dispositif adapté, tel qu’une sonde étalonnée ; direction, sens et intensité sont des informations distinctes.
terminale-laplace|Un conducteur de 0,20 m parcouru par 2 A est perpendiculaire à un champ uniforme de 0,50 T. Calculer la force de Laplace.|La norme vaut F=BIL sinθ=0,50×2×0,20=0,20 N puisque θ=90°. La direction et le sens se déterminent avec la relation vectorielle adaptée. Un conducteur parallèle au champ aurait une force nulle dans ce modèle.
terminale-induction-rl|Une bobine idéale de 0,20 H voit son courant augmenter à 3 A/s. Donner la f.é.m. induite orientée selon la loi de Faraday.|e=−L di/dt=−0,20×3=−0,60 V dans la convention indiquée. Le signe traduit l’opposition à la variation du courant, conformément à la loi de Lenz. Il faut distinguer cette f.é.m. de la tension aux bornes écrite en convention récepteur.
terminale-dipole-rc|Un circuit RC a R=10 kΩ et C=20 µF. Calculer la constante de temps.|τ=RC=10 000×20×10⁻⁶=0,20 s. Au bout de τ, une charge idéale à partir de zéro atteint environ 63 % de sa valeur finale. τ n’est pas un temps de charge totale, qui n’est atteint qu’asymptotiquement dans le modèle exponentiel.
terminale-oscillations-electriques|Dans un circuit LC idéal, C=10 µF est initialement chargé sous 4 V et L=0,10 H. Calculer l’énergie totale et le courant maximal.|L’énergie initiale vaut ½CU²=0,5×10×10⁻⁶×16=8,0×10⁻⁵ J. Quand elle est entièrement dans la bobine, ½LI_max²=E. Donc I_max=√(2E/L)=0,040 A. Le bilan suppose une résistance nulle et un courant initial nul.
terminale-photoelectrique|Un photon a une énergie de 3 eV et le travail d’extraction vaut 2 eV. Quelle énergie cinétique maximale prévoit le modèle photoélectrique ?|E_c,max=hν−W=3−2=1 eV. Si l’énergie du photon était inférieure au travail d’extraction, aucune émission ne serait prévue par ce modèle, même avec une intensité plus élevée. L’énergie maximale dépend de la fréquence.
terminale-niveaux-energie|Un atome passe d’un niveau de −2 eV à un niveau de −5 eV. Absorbe-t-il ou émet-il un photon ?|L’énergie de l’atome diminue de 3 eV. Il émet donc un photon d’énergie 3 eV dans le modèle de transition radiative. L’énergie d’un photon est positive ; on prend la différence entre niveau initial et niveau final pour une émission.
terminale-reactions-nucleaires|Lors d’une désintégration alpha, comment évoluent A et Z du noyau père ?|Une particule alpha est un noyau d’hélium de nombres A=4 et Z=2. Le noyau fils a donc A_f=A_p−4 et Z_f=Z_p−2. On vérifie la conservation du nombre de nucléons et de la charge dans l’équation nucléaire.
terminale-alcools|Que peut donner l’oxydation ménagée d’un alcool primaire ?|Selon les conditions, elle peut conduire à un aldéhyde puis à un acide carboxylique si l’oxydation se poursuit. La classe de l’alcool et les conditions expérimentales doivent être précisées. Un alcool secondaire conduit classiquement à une cétone dans ce cadre.
terminale-amines|Pourquoi une amine peut-elle se comporter comme une base de Brønsted ?|Le doublet libre de l’azote peut capter un proton H⁺. Une amine RNH₂ forme alors l’ion ammonium RNH₃⁺. Il faut distinguer capacité à capter un proton et force effective de la base, qui dépend de la structure et du milieu.
terminale-acides-carboxyliques|Quels types de réactifs interviennent dans une estérification usuelle, et quel autre produit accompagne l’ester ?|Un acide carboxylique réagit avec un alcool pour donner un ester et de l’eau. La transformation est généralement limitée par un équilibre dans les conditions scolaires usuelles. Un catalyseur accélère l’approche de l’équilibre sans, à lui seul, modifier sa position à température donnée.
terminale-cinetique-chimique|Augmenter la température peut accélérer une réaction. Cela garantit-il un rendement final plus élevé ?|Non. La vitesse et l’état final d’équilibre sont deux questions différentes. Une température plus élevée peut augmenter la vitesse, tandis que l’évolution du rendement à l’équilibre dépend de la thermodynamique de la réaction. Un catalyseur ne déplace pas l’équilibre.
terminale-ph-autoprotolyse|À 25 °C, si [H₃O⁺]=10⁻⁵ mol/L, calculer le pH et [OH⁻] dans le modèle usuel.|pH=−log(10⁻⁵)=5. Avec K_e=10⁻¹⁴, [OH⁻]=K_e/[H₃O⁺]=10⁻⁹ mol/L. Le produit ionique dépend de la température ; ces valeurs numériques supposent 25 °C et le modèle des solutions suffisamment diluées.
terminale-acide-base-forts|Une solution d’acide fort monoprotique a C=2,0×10⁻³ mol/L. Quel pH prévoit le modèle de dissociation totale à 25 °C ?|Dans ce domaine, [H₃O⁺]≈C. pH≈−log(2,0×10⁻³)=3−log2≈2,70. L’exposant seul ne suffit pas si le coefficient diffère de 1. Cette approximation suppose une solution suffisamment diluée et une contribution de l’eau négligeable devant celle de l’acide.
terminale-acides-bases-faibles|Pourquoi ne peut-on pas poser automatiquement [H₃O⁺]=C pour un acide faible ?|Sa réaction avec l’eau est limitée : une partie de l’acide reste sous sa forme moléculaire. On doit utiliser l’équilibre, le bilan de matière et la constante d’acidité avec les approximations justifiées. Une faible concentration ne signifie pas automatiquement un acide faible ; force et concentration sont distinctes.
terminale-tampon-dosage|Pourquoi une solution contenant un acide faible et sa base conjuguée peut-elle atténuer une petite addition d’acide ?|La base conjuguée consomme une partie des ions oxonium ajoutés et se transforme en acide. Le rapport des deux formes change modérément si les quantités ajoutées restent faibles devant celles du tampon. L’effet tampon a une capacité limitée ; il ne maintient pas le pH contre une addition arbitraire.
terminale-acides-amines|Pourquoi un acide aminé peut-il présenter une forme zwitterionique ?|Il possède un groupe acide et un groupe basique pouvant être simultanément sous les formes COO⁻ et NH₃⁺. La charge totale peut alors être nulle tout en comportant des charges locales. La forme prédominante dépend du pH et des constantes acido-basiques des groupes concernés.
terminale-complexes|Calculer (1+i)(1−i) et le module de 1+i.|Le produit vaut 1−i²=2 puisque i²=−1. Le module vaut √(1²+1²)=√2. Le produit d’un complexe par son conjugué est égal au carré de son module, ce qui fournit une vérification immédiate.
terminale-derivation|Pour f(x)=x³−3x, donner les points critiques et préciser si chacun est un extremum.|f′(x)=3x²−3=3(x−1)(x+1). Le signe passe de positif à négatif en −1 : maximum local f(−1)=2. Il passe de négatif à positif en 1 : minimum local f(1)=−2. Le changement de signe, et pas seulement f′=0, justifie les extrema.
terminale-exponentielle|Résoudre e^(2x)=e³ dans ℝ.|La fonction exponentielle est strictement croissante, donc injective : 2x=3 et x=3/2. On peut aussi appliquer le logarithme aux deux membres positifs. Il ne faut pas confondre e^(2x) et 2e^x.
terminale-logarithme|Résoudre ln(x−1)=ln3 en précisant le domaine.|Le logarithme impose x−1>0, donc x>1. Son injectivité donne x−1=3, soit x=4. Cette valeur appartient au domaine. Déterminer le domaine avant les transformations évite de conserver des solutions interdites.
terminale-limites|Calculer la limite de (2x²+1)/(x²−3) lorsque x tend vers +∞.|En divisant numérateur et dénominateur par x², on obtient (2+1/x²)/(1−3/x²), qui tend vers 2. La forme ∞/∞ n’est pas une réponse : elle indique qu’il faut transformer l’expression pour comparer les termes dominants.
terminale-primitives-integrales|Calculer l’intégrale de 0 à 2 de 3x² dx.|Une primitive est F(x)=x³. L’intégrale vaut F(2)−F(0)=8. Une constante ajoutée à la primitive se simplifie dans la différence. L’aire géométrique coïncide ici avec l’intégrale puisque la fonction est positive sur l’intervalle.
terminale-probabilites|Deux événements indépendants ont P(A)=0,4 et P(B)=0,5. Calculer P(A∩B).|L’indépendance donne P(A∩B)=P(A)P(B)=0,20. Elle doit être donnée ou démontrée ; elle ne résulte pas du simple fait que deux événements sont distincts. Des événements incompatibles de probabilités non nulles ne sont pas indépendants.
terminale-statistiques-deux-variables|Une forte corrélation entre deux variables prouve-t-elle que l’une cause l’autre ?|Non. Une association peut venir d’un facteur commun, d’un biais ou du hasard. La corrélation décrit une relation statistique, et la causalité exige un dispositif et des arguments supplémentaires. Une extrapolation hors du domaine observé reste particulièrement fragile.
'''
EXTRAS.update({line.split('|',2)[0]: tuple(line.split('|',2)[1:]) for line in RAW_TERMINALE.strip().splitlines()})
